### ISSUE TITLE
cifar10/norm_all_batch_data.npy

### ISSUE THREAD

**Issue by vickyqi7** [icmpnorequest/MLSec#1]
Excuse me，I read the code you wrote and it feels good, but there is no such file：cifar10/norm_all_batch_data.npy
Without it ,I can't run the Experiment_CIFAR10.py
Can you provide this file？Thank you very much！

**Comment by icmpnorequest** [comment]
@vickyqi7 The `norm_all_batch_data.npy` is too large to upload on Github. I have updated README.md and you could download it via BaiduNet. May it would help you. When running the code, please be aware of the file path.

**Comment by vickyqi7** [comment]
Thank you very much~

**Comment by icmpnorequest** [comment]
My pleasure. If you don't have other issues, I would close this issue.
