### ISSUE TITLE
cifar10/norm_all_batch_data.npy

### ISSUE THREAD

**Issue by tanaymisra0408** [icmpnorequest/MLSec#3]
The link which you provided in the readme file is not opening . Can you give me any other link from where I can get the aforementioned file.

**Comment by icmpnorequest** [comment]
@tanaymisra0408
Sorry for reply so late. I tried to open the [link](https://pan.baidu.com/s/1uZaZhVYUiRXi3resfuJoiA) and it works. Maybe you could try again, and I will upload it to Google Drive later.
